### ISSUE TITLE
Should we make nbresuse an official jupyter project?

### ISSUE THREAD

**Issue by lresende** [yuvipanda/jupyter-resource-usage#62]
We are seeing good adoption of nbresuse, should we move this to Jupyter org?

**Comment by jtpio** [comment]
Thanks @lresende for opening this.

This sounds like a good idea and is also what the discussion in https://github.com/yuvipanda/nbresuse/issues/58 is heading towards.

We could then group all the frontend extensions in one place to make it easier for users to discover and install.

**Comment by jtpio** [comment]
We discussed this during the Jupyter Server meeting today: https://github.com/jupyter-server/jupyter_server/issues/126

The consensus was that the [jupyter-server](https://github.com/jupyter-server) would be a good home for this project. Moving it there would also help with the long-term goal of baking metrics in the server and “closer” to kernels.

@yuvipanda is it ok for you to move the repo to the [jupyter-server](https://github.com/jupyter-server) GitHub organization?

cc @ajbozarth @ZSailer @kevin-bates @mlucool

**Comment by yuvipanda** [comment]
YESSS!

Let's continue this conversation in https://github.com/jupyter-server/team-compass/issues/1
